const envConst = {
	NODE_ENV: process.env.NODE_ENV,
	X_API_KEY: process.env.NEXT_PUBLIC_X_API_KEY,

	SANITY_TOKEN: process.env.NEXT_PUBLIC_SANITY_TOKEN,
	SANITY_PROJECT_ID: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
	SANITY_DATASET: process.env.NEXT_PUBLIC_SANITY_DATASET,

	GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
	GTM_ID: process.env.NEXT_PUBLIC_GTM_ID,

	FACEBOOK_PAGE_ID: process.env.NEXT_PUBLIC_FACEBOOK_PAGE_ID,
	ENABLE_FB_CHAT: process.env.NEXT_PUBLIC_ENABLE_FB_CHAT,

	TELEGRAM_BOT_TOKEN: process.env.NEXT_PUBLIC_TELEGRAM_BOT_TOKEN,
	TELEGRAM_CHAT_ID: process.env.NEXT_PUBLIC_TELEGRAM_CHAT_ID,

	ENABLE_UMAMI: process.env.NEXT_PUBLIC_ENABLE_UMAMI,
};

export default envConst;
